# Generated by Django 3.0.7 on 2020-06-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20200630_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='spotlight',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
