# Generated by Django 3.0.7 on 2020-06-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_collection_spotlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='url',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
