# Generated by Django 3.0.7 on 2020-07-01 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20200701_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='contact',
            field=models.ForeignKey(default='d014eb9e-e068-4346-886f-1342477a929d', on_delete=django.db.models.deletion.CASCADE, to='portfolio.Contact'),
            preserve_default=False,
        ),
    ]
