# Generated by Django 3.0.7 on 2020-07-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20200703_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='detail_view',
            field=models.CharField(default='portfolio:project-detail', max_length=64),
            preserve_default=False,
        ),
    ]
