# Generated by Django 3.0.7 on 2020-07-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_section_detail_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='detail_view',
        ),
        migrations.AddField(
            model_name='sectiontype',
            name='detail_view',
            field=models.CharField(default='portfolio:project-detail', max_length=64),
            preserve_default=False,
        ),
    ]
