# Generated by Django 3.0.7 on 2020-07-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_auto_20200703_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseentry',
            name='detail_view',
            field=models.CharField(choices=[('portfolio:project-detail', 'Project View'), ('portfolio:photo-detail', 'Photo View'), ('portfolio:entry-detail', 'Base View')], default='portfolio.views.BaseEntryView', max_length=64),
        ),
    ]
