# Generated by Django 3.0.7 on 2020-07-03 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_auto_20200703_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='nav_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.NavLink'),
        ),
    ]
