# Generated by Django 3.0.7 on 2020-07-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_section_nav_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='view',
            field=models.CharField(choices=[('portfolio:project-detail', 'Project View'), ('portfolio:photo-detail', 'Photo View'), ('portfolio:entry-detail', 'Base View')], default='portfolio.views.BaseEntryView', max_length=64),
        ),
    ]
