# Generated by Django 3.0.7 on 2020-07-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_auto_20200703_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
