# Generated by Django 3.0.7 on 2020-07-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0034_auto_20200703_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='collection',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
