# Generated by Django 3.0.7 on 2020-07-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0035_auto_20200703_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerlink',
            name='footer_section',
        ),
        migrations.AddField(
            model_name='footerlink',
            name='position',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], null=True, unique=True),
        ),
    ]
