# Generated by Django 3.0.7 on 2020-07-05 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0039_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.RenameField(
            model_name='baseentry',
            old_name='section',
            new_name='parent_section',
        ),
        migrations.AlterField(
            model_name='baseentry',
            name='detail_view',
            field=models.CharField(choices=[('portfolio:project-detail', 'Project Detail View'), ('portfolio:project-list', 'Project List View'), ('portfolio:photo-detail', 'Photo View'), ('portfolio:entry-detail', 'Base View')], default='portfolio.views.BaseEntryView', max_length=64),
        ),
        migrations.AlterField(
            model_name='link',
            name='view',
            field=models.CharField(choices=[('portfolio:project-detail', 'Project Detail View'), ('portfolio:project-list', 'Project List View'), ('portfolio:photo-detail', 'Photo View'), ('portfolio:entry-detail', 'Base View')], default='portfolio:project-detail', max_length=64),
        ),
        migrations.CreateModel(
            name='Translatable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translantions_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.TranslationsGroup')),
            ],
        ),
    ]
