# Generated by Django 3.0.7 on 2020-07-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0041_auto_20200705_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseentry',
            old_name='translantions_group',
            new_name='translations_group',
        ),
        migrations.AddField(
            model_name='baseentry',
            name='lang',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English'), ('nl', 'Dutch')], default='en', max_length=5),
        ),
    ]
