# Generated by Django 3.0.7 on 2020-07-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0046_auto_20200706_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='nav_link',
        ),
        migrations.RemoveField(
            model_name='sectioncommon',
            name='nav_link',
        ),
    ]
