# Generated by Django 3.0.7 on 2020-07-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0047_remove_sectioncommon_nav_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='navlink',
        ),
        migrations.DeleteModel(
            name='footerlink',
        ),
        migrations.DeleteModel(
            name='Link',
        ),

    ]
