# Generated by Django 3.0.7 on 2020-07-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0049_footerlink_navlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='position',
            field=models.CharField(choices=[('navbar-0', 'navbar 0'), ('navbar-1', 'navbar 1'), ('navbar-2', 'navbar 2'), ('navbar-3', 'navbar 3'), ('navbar-4', 'navbar 4'), ('navbar-5', 'navbar 5'), ('navbar-6', 'navbar 6'), ('navbar-7', 'navbar 7'), ('navbar-8', 'navbar 8'), ('navbar-9', 'navbar 9'), ('footer-0', 'footer 0'), ('footer-1', 'footer 1'), ('footer-2', 'footer 2'), ('footer-3', 'footer 3'), ('footer-4', 'footer 4'), ('footer-5', 'footer 5'), ('footer-6', 'footer 6'), ('footer-7', 'footer 7'), ('footer-8', 'footer 8'), ('footer-9', 'footer 9')], max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='navlink',
            name='position',
            field=models.CharField(choices=[('navbar-0', 'navbar 0'), ('navbar-1', 'navbar 1'), ('navbar-2', 'navbar 2'), ('navbar-3', 'navbar 3'), ('navbar-4', 'navbar 4'), ('navbar-5', 'navbar 5'), ('navbar-6', 'navbar 6'), ('navbar-7', 'navbar 7'), ('navbar-8', 'navbar 8'), ('navbar-9', 'navbar 9'), ('footer-0', 'footer 0'), ('footer-1', 'footer 1'), ('footer-2', 'footer 2'), ('footer-3', 'footer 3'), ('footer-4', 'footer 4'), ('footer-5', 'footer 5'), ('footer-6', 'footer 6'), ('footer-7', 'footer 7'), ('footer-8', 'footer 8'), ('footer-9', 'footer 9')], max_length=8, null=True, unique=True),
        ),
    ]
