# Generated by Django 3.0.7 on 2020-07-06 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0050_auto_20200706_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.CreateModel(
            name='ExhibitionPieceCommon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('created', models.DateTimeField()),
                ('spotlight', models.BooleanField()),
                ('detail_view', models.CharField(choices=[('portfolio:project-detail', 'Project Detail View'), ('portfolio:project-list', 'Project List View'), ('portfolio:photo-detail', 'Photo View'), ('portfolio:entry-detail', 'Base View')], default='portfolio.views.BaseEntryView', max_length=64)),
                ('parent_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Section')),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitionPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('de', 'German'), ('en', 'English'), ('nl', 'Dutch')], default='en', max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField()),
                ('common', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_pieces', to='portfolio.ExhibitionPieceCommon')),
                ('translations_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.TranslationsGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
