# Generated by Django 3.0.7 on 2020-07-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0052_auto_20200706_1235'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='baseentry',
            unique_together={('translations_group', 'lang')},
        ),
        migrations.AlterUniqueTogether(
            name='exhibitionpiece',
            unique_together={('translations_group', 'lang')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('translations_group', 'lang')},
        ),
    ]
