# Generated by Django 3.0.7 on 2020-07-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0053_auto_20200706_1310'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='baseentry',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='exhibitionpiece',
            unique_together={('common', 'lang')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('common', 'lang')},
        ),
        migrations.RemoveField(
            model_name='baseentry',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='baseentry',
            name='translations_group',
        ),
        migrations.RemoveField(
            model_name='exhibitionpiece',
            name='translations_group',
        ),
        migrations.RemoveField(
            model_name='section',
            name='translations_group',
        ),
        migrations.DeleteModel(
            name='TranslationsGroup',
        ),
    ]
