# Generated by Django 3.0.7 on 2020-07-06 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0054_auto_20200706_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NavBarEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='footerlink',
            name='footer_edit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.FooterEdit'),
        ),
        migrations.AddField(
            model_name='navlink',
            name='navbar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.NavBarEdit'),
        ),
    ]
