# Generated by Django 3.0.7 on 2020-07-06 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0055_auto_20200706_1729'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NavBarEdit',
            new_name='LinkEdit',
        ),
        migrations.RemoveField(
            model_name='footerlink',
            name='footer_edit',
        ),
        migrations.RemoveField(
            model_name='navlink',
            name='navbar',
        ),
        migrations.AddField(
            model_name='footerlink',
            name='link_edit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footer_links', to='portfolio.LinkEdit'),
        ),
        migrations.AddField(
            model_name='navlink',
            name='link_edit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navbar_links', to='portfolio.LinkEdit'),
        ),
        migrations.DeleteModel(
            name='FooterEdit',
        ),
    ]
