# Generated by Django 3.0.7 on 2020-07-06 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0056_auto_20200706_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlink',
            name='external',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='link_for',
            field=models.CharField(choices=[('section', 'Section'), ('page', 'Page'), ('external', 'External')], max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Page'),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Section'),
        ),
        migrations.AddField(
            model_name='navlink',
            name='external',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='navlink',
            name='link_for',
            field=models.CharField(choices=[('section', 'Section'), ('page', 'Page'), ('external', 'External')], max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='navlink',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Page'),
        ),
        migrations.AddField(
            model_name='navlink',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Section'),
        ),
    ]
