# Generated by Django 3.0.7 on 2020-07-06 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0057_auto_20200706_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='external',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Page'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Section'),
        ),
        migrations.AlterField(
            model_name='navlink',
            name='external',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='navlink',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Page'),
        ),
        migrations.AlterField(
            model_name='navlink',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Section'),
        ),
    ]
