# Generated by Django 3.0.7 on 2020-07-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0059_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='link_for',
            field=models.CharField(choices=[('page', 'Page'), ('section', 'Section'), ('detail', 'Detail'), ('list', 'Collection'), ('external', 'External')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='navlink',
            name='link_for',
            field=models.CharField(choices=[('page', 'Page'), ('section', 'Section'), ('detail', 'Detail'), ('list', 'Collection'), ('external', 'External')], max_length=24, null=True),
        ),
    ]
