# Generated by Django 3.0.7 on 2020-07-06 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0060_auto_20200706_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='link_for',
            field=models.CharField(choices=[('page', 'Page'), ('section', 'Section'), ('external', 'External')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='navlink',
            name='link_for',
            field=models.CharField(choices=[('page', 'Page'), ('section', 'Section'), ('external', 'External')], max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.PageType'),
        ),
    ]
