# Generated by Django 3.0.7 on 2020-07-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0062_auto_20200706_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='overwrite_view_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='view_name',
            field=models.CharField(default='view_name', editable=False, max_length=64),
            preserve_default=False,
        ),
    ]
