# Generated by Django 3.0.7 on 2020-07-06 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0063_auto_20200706_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='nav_bar_link',
        ),
        migrations.RemoveField(
            model_name='sectioncommon',
            name='nav_bar_link',
        ),
        migrations.AddField(
            model_name='sectioncommon',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Page'),
        ),
    ]
