# Generated by Django 3.0.7 on 2020-07-06 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0065_auto_20200706_1903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExhibitionPiece',
        ),
    ]
