# Generated by Django 3.0.7 on 2020-07-06 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0066_delete_exhibitionpiece'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseentry',
            name='common',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_pieces', to='portfolio.ExhibitionPieceCommon'),
        ),
        migrations.AddField(
            model_name='baseentry',
            name='lang',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English'), ('nl', 'Dutch')], default='en', max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='baseentry',
            unique_together={('common', 'lang')},
        ),
    ]
