# Generated by Django 3.0.7 on 2020-07-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0067_auto_20200706_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionpiececommon',
            name='friendly_name',
            field=models.CharField(default='demo_project', max_length=64),
            preserve_default=False,
        ),
    ]
