# Generated by Django 3.0.7 on 2020-07-06 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0069_auto_20200706_2051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseEntry',
            new_name='CollectionItem',
        ),
        migrations.RenameModel(
            old_name='ExhibitionPieceCommon',
            new_name='CollectionItemCommon',
        ),
    ]
