# Generated by Django 3.0.7 on 2020-07-06 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0070_auto_20200706_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionitem',
            options={'verbose_name': 'Item Translation', 'verbose_name_plural': 'Item Translations'},
        ),
        migrations.AlterModelOptions(
            name='collectionitemcommon',
            options={'verbose_name': 'Collection Item', 'verbose_name_plural': 'Collection Items'},
        ),
        migrations.AlterModelOptions(
            name='footerlink',
            options={'verbose_name': 'Footer Link', 'verbose_name_plural': 'Footer Links'},
        ),
        migrations.AlterModelOptions(
            name='linkedit',
            options={'verbose_name': 'Page Link', 'verbose_name_plural': 'Page Links'},
        ),
        migrations.AlterModelOptions(
            name='navlink',
            options={'verbose_name': 'Navigation Link', 'verbose_name_plural': 'Navigation Links'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Single Page', 'verbose_name_plural': 'Single Pages'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Section Translation', 'verbose_name_plural': 'Sections Translations'},
        ),
        migrations.AlterModelOptions(
            name='sectioncommon',
            options={'verbose_name': 'Page Section', 'verbose_name_plural': 'Page Sections'},
        ),
        migrations.AlterUniqueTogether(
            name='collectionitem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('url', models.CharField(max_length=256)),
                ('view', models.CharField(choices=[('portfolio:project-detail', 'Project Detail View'), ('portfolio:project-list', 'Project List View'), ('portfolio:photo-detail', 'Photo View'), ('portfolio:entry-detail', 'Base View')], default='portfolio:project-detail', max_length=64)),
                ('position', models.CharField(choices=[('navbar-0', 'navbar 0'), ('navbar-1', 'navbar 1'), ('navbar-2', 'navbar 2'), ('navbar-3', 'navbar 3'), ('navbar-4', 'navbar 4'), ('navbar-5', 'navbar 5'), ('navbar-6', 'navbar 6'), ('navbar-7', 'navbar 7'), ('navbar-8', 'navbar 8'), ('navbar-9', 'navbar 9'), ('footer-0', 'footer 0'), ('footer-1', 'footer 1'), ('footer-2', 'footer 2'), ('footer-3', 'footer 3'), ('footer-4', 'footer 4'), ('footer-5', 'footer 5'), ('footer-6', 'footer 6'), ('footer-7', 'footer 7'), ('footer-8', 'footer 8'), ('footer-9', 'footer 9')], max_length=8, null=True, unique=True)),
                ('link_for', models.CharField(choices=[('page', 'Page'), ('section', 'Section'), ('external', 'External')], max_length=24, null=True)),
                ('external', models.URLField(blank=True, null=True)),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Icon')),
                ('link_edit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_links', to='portfolio.LinkEdit')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Page')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Section')),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
            },
        ),
        migrations.CreateModel(
            name='PageCommon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=64)),
                ('view_name', models.CharField(editable=False, max_length=64)),
                ('overwrite_view_name', models.CharField(blank=True, max_length=64, null=True)),
                ('page_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.PageType')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
    ]
