# Generated by Django 3.0.7 on 2020-07-06 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0071_auto_20200706_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='common',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='portfolio.CollectionItemCommon'),
        ),
    ]
