# Generated by Django 3.0.7 on 2020-07-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0072_auto_20200706_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='url',
            field=models.CharField(blank=True, default='/', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='navlink',
            name='url',
            field=models.CharField(blank=True, default='/', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.CharField(blank=True, default='/', editable=False, max_length=256),
        ),
    ]
