# Generated by Django 3.0.7 on 2020-07-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0074_collectionitem_image_alttext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='image_alttext',
            field=models.TextField(default=''),
        ),
    ]
