# Generated by Django 3.0.7 on 2020-07-09 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0075_auto_20200706_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='overwrite_view_name',
        ),
        migrations.RemoveField(
            model_name='page',
            name='page_type',
        ),
        migrations.RemoveField(
            model_name='page',
            name='template_name',
        ),
        migrations.RemoveField(
            model_name='page',
            name='view_name',
        ),
        migrations.RemoveField(
            model_name='pagecommon',
            name='overwrite_view_name',
        ),
        migrations.RemoveField(
            model_name='pagecommon',
            name='view_name',
        ),
        migrations.AddField(
            model_name='page',
            name='common',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='portfolio.PageCommon'),
        ),
        migrations.AddField(
            model_name='pagetype',
            name='overwrite_view_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='pagetype',
            name='template_name',
            field=models.CharField(default='page.html', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagetype',
            name='view_name',
            field=models.CharField(default='PageView', editable=False, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sectioncommon',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='portfolio.PageCommon'),
        ),
    ]
