# Generated by Django 3.0.7 on 2020-07-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0076_auto_20200709_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecommon',
            name='friendly_name',
            field=models.CharField(default='home_page', max_length=64),
            preserve_default=False,
        ),
    ]
