# Generated by Django 3.0.7 on 2020-07-09 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0077_pagecommon_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.PageCommon'),
        ),
        migrations.AlterField(
            model_name='navlink',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.PageCommon'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.PageCommon'),
        ),
    ]
