# Generated by Django 3.0.7 on 2020-07-09 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0078_auto_20200709_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='lang',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English'), ('nl', 'Dutch')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='page',
            name='common',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.PageCommon'),
        ),
    ]
