# Generated by Django 3.0.7 on 2020-07-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0079_auto_20200709_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectioncommon',
            name='position',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], null=True),
        ),
        migrations.AlterUniqueTogether(
            name='sectioncommon',
            unique_together={('page', 'position')},
        ),
    ]
