# Generated by Django 3.0.7 on 2020-07-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0081_auto_20200710_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='view',
            field=models.CharField(choices=[('portfolio:detail', 'Detail View'), ('portfolio:collection', 'Collection View'), ('portfolio:page', 'Page View')], default='portfolio:detail', max_length=64),
        ),
        migrations.AlterField(
            model_name='navlink',
            name='view',
            field=models.CharField(choices=[('portfolio:detail', 'Detail View'), ('portfolio:collection', 'Collection View'), ('portfolio:page', 'Page View')], default='portfolio:detail', max_length=64),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='view',
            field=models.CharField(choices=[('portfolio:detail', 'Detail View'), ('portfolio:collection', 'Collection View'), ('portfolio:page', 'Page View')], default='portfolio:detail', max_length=64),
        ),
    ]
