# Generated by Django 3.0.7 on 2020-07-10 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0083_auto_20200710_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='detail_slug',
            field=models.SlugField(default='project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collectionitemcommon',
            name='parent_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.SectionCommon'),
        ),
    ]
