# Generated by Django 3.0.7 on 2020-07-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0084_auto_20200710_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='detail_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
