# Generated by Django 3.0.7 on 2020-07-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0085_auto_20200710_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecommon',
            name='footer_link',
            field=models.BooleanField(default=True),
        ),
    ]
