# Generated by Django 3.0.7 on 2020-07-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0086_pagecommon_footer_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecommon',
            name='footer_position',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], null=True, unique=True),
        ),
    ]
