# Generated by Django 3.0.7 on 2020-07-11 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0087_pagecommon_footer_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactResponseCommon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.CharField(max_length=32)),
                ('action_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.PageType')),
            ],
        ),
        migrations.CreateModel(
            name='ContactResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('de', 'German'), ('en', 'English'), ('nl', 'Dutch')], default='en', max_length=5)),
                ('name', models.CharField(max_length=32)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
                'unique_together': {('lang', 'slug')},
            },
        ),
    ]
