# Generated by Django 3.0.7 on 2020-07-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0089_contactresponse_common'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactresponsecommon',
            name='action_arg',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
