# Generated by Django 3.0.7 on 2020-07-11 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0091_auto_20200711_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactresponsecommon',
            name='action_arg',
        ),
        migrations.RemoveField(
            model_name='contactresponsecommon',
            name='action_page',
        ),
        migrations.CreateModel(
            name='ContactResponseAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('DELETE', 'DELETE')], max_length=7)),
                ('argument', models.CharField(blank=True, max_length=32, null=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Page')),
            ],
        ),
        migrations.AddField(
            model_name='contactresponsecommon',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.ContactResponseAction'),
        ),
    ]
