# Generated by Django 3.0.7 on 2020-07-11 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0092_auto_20200711_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactresponseaction',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.PageCommon'),
        ),
    ]
