# Generated by Django 3.0.7 on 2020-07-11 22:15

from django.db import migrations, models
import portfolio.validators


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0093_auto_20200711_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='colour',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[portfolio.validators.validate_colour_code]),
        ),
    ]
