# Generated by Django 3.0.7 on 2020-07-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0096_auto_20200711_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='position',
            field=models.CharField(blank=True, choices=[('deg270', '12:00'), ('deg315', '01:30'), ('deg0', '03:00'), ('deg45', '04:30'), ('deg90', '06:00'), ('deg135', '07:30'), ('deg180', '09:00'), ('deg225', '10:30')], max_length=6, null=True, unique=True),
        ),
    ]
