# Generated by Django 3.0.7 on 2020-07-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0098_icon_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
