# Generated by Django 3.0.7 on 2020-07-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0100_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagecommon',
            name='template_name',
        ),
    ]
