version: '3'

services:
  web:
    container_name: django
    build: homepage/
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment: 
      - DEV_MODE=True