"""
Django settings for homepage project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
import logging.config
import os
import random

from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv
from get_docker_secret import get_docker_secret

# Load environment variables from .env file
load_dotenv()

DEFAULTS = {

}
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


DEV_MODE = os.getenv('DEV_MODE', False)
DATABASE = os.getenv('DATABASE', 'sqlite')
HOST = os.getenv('HOST', '127.0.0.1').split(",")
print("DEV_MODE:", DEV_MODE)
if DEV_MODE:
    PROTO = 'http'

    PORT = '8000'
    MEDIA_URL = os.getenv('MEDIA_URL', '/media/')
    MEDIA_ROOT = os.getenv('MEDIA_ROOT', os.path.join(BASE_DIR, 'media/'))

    if DATABASE == 'sqlite':
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
            }
        }
    elif DATABASE == 'postgres':
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": get_docker_secret('postgres_db'),
                "USER": get_docker_secret('postgres_user'),
                "PASSWORD": get_docker_secret('postgres_password'),
                "HOST": get_docker_secret('database_host'),
                "PORT": get_docker_secret('database_port'),
            }
        }
else:
    print('Production Settings')
    PROTO = 'https'
    MEDIA_URL = os.getenv('MEDIA_URL', f'{PROTO}://media.{HOST[0]}')
    MEDIA_ROOT = os.getenv('MEDIA_ROOT', '/var/www/media/')
    if DATABASE == 'sqlite':
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
            }
        }
    elif DATABASE == 'postgres':
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": get_docker_secret('postgres_db'),
                "USER": get_docker_secret('postgres_user'),
                "PASSWORD": get_docker_secret('postgres_password'),
                "HOST": get_docker_secret('database_host'),
                "PORT": get_docker_secret('database_port'),
            }
        }
        """ DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": os.getenv('POSTGRES_DB'),
                "USER": os.getenv('POSTGRES_USER'),
                "PASSWORD": os.getenv('POSTGRES_PASSWORD'),
                "HOST": os.getenv('DATABASE_HOST'),
                "PORT": os.getenv('DATABASE_PORT'),
            }
        } """
    # Logging Configuration

    # Clear prev config
    LOGGING_CONFIG = None

    # Get loglevel from env
    LOGLEVEL = os.getenv('DJANGO_LOGLEVEL', 'info').upper()

    logging.config.dictConfig({
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'console': {
                'format': '%(asctime)s %(levelname)s [%(name)s:%(lineno)s] %(module)s %(process)d %(thread)d %(message)s',
            },
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'console',
            },
        },
        'loggers': {
            '': {
                'level': LOGLEVEL,
                'handlers': ['console', ],
            },
        },
    })

    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/3.0/howto/static-files/


STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = os.getenv('STATIC_URL', '/static/')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
""" SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', ''.join(random.SystemRandom().choice(
    'abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)') for i in range(50))) """

SECRET_KEY = get_docker_secret('django_secret_key', default=''.join(random.SystemRandom().choice(
    'abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)') for i in range(50)))
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = DEV_MODE

ALLOWED_HOSTS = HOST


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'portfolio.apps.PortfolioConfig',
    'django_inlinecss'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'homepage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media'
            ],
        },
    },
]

WSGI_APPLICATION = 'homepage.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('de', _('German')),
    ('en', _('English')),
    ('nl', _('Dutch'))
]

LOCALE_PATHS = [
    f'{BASE_DIR}/locale',
]

LANGUAGE_COOKIE_NAME = 'djangolanguage'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Emails
EMAIL_USE_TLS = True
EMAIL_HOST = get_docker_secret('email_host')
EMAIL_HOST_USER = get_docker_secret('email_host_user')
EMAIL_HOST_PASSWORD = get_docker_secret('email_host_password')
EMAIL_PORT = get_docker_secret('email_port', default=587)
EMAIL_CONTACT_ADDRESS = get_docker_secret('email_contact_address')
DEFAULT_FROM_EMAIL = get_docker_secret('default_from_email')
#EMAIL_HOST = os.getenv("EMAIL_HOST")
#EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
#EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
#EMAIL_PORT = os.getenv("EMAIL_PORT", 587)
#EMAIL_CONTACT_ADDRESS = os.getenv('EMAIL_CONTACT_ADDRESS')
#DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

MAX_PAGES = 10
MAX_SECTIONS = 10
MAX_NAVLINKS = 10
MAX_FOOTERLINKS = 10
