CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_user_groups_user_id_group_id_94350c0c_uniq" ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
CREATE UNIQUE INDEX "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "action_time" datetime NOT NULL, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0));
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE IF NOT EXISTS "auth_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(30) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "last_name" varchar(150) NOT NULL);
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE TABLE IF NOT EXISTS "portfolio_contact" ("email_address" varchar(254) NOT NULL, "email_confirmed" bool NOT NULL, "id" char(32) NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "portfolio_sectiontype" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(64) NOT NULL, "template_name" varchar(64) NOT NULL, "default_position" integer NOT NULL);
CREATE TABLE IF NOT EXISTS "portfolio_setting" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "key" varchar(256) NOT NULL, "value" varchar(1024) NOT NULL);
CREATE TABLE IF NOT EXISTS "portfolio_linkedit" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT);
CREATE TABLE IF NOT EXISTS "portfolio_collectionitem" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL, "slug" varchar(100) NOT NULL, "description" text NOT NULL, "common_id" integer NULL REFERENCES "portfolio_collectionitemcommon" ("id") DEFERRABLE INITIALLY DEFERRED, "lang" varchar(5) NOT NULL, "image_alttext" text NOT NULL);
CREATE INDEX "portfolio_collectionitem_slug_c87816ef" ON "portfolio_collectionitem" ("slug");
CREATE INDEX "portfolio_collectionitem_common_id_7ea04dce" ON "portfolio_collectionitem" ("common_id");
CREATE TABLE IF NOT EXISTS "portfolio_pagetype" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(24) NOT NULL, "overwrite_view_name" varchar(64) NULL, "template_name" varchar(64) NOT NULL, "view_name" varchar(64) NOT NULL);
CREATE TABLE IF NOT EXISTS "portfolio_page" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(24) NOT NULL, "slug" varchar(50) NULL, "lang" varchar(5) NOT NULL, "common_id" integer NULL REFERENCES "portfolio_pagecommon" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "portfolio_page_slug_fef7176f" ON "portfolio_page" ("slug");
CREATE INDEX "portfolio_page_common_id_15344920" ON "portfolio_page" ("common_id");
CREATE TABLE IF NOT EXISTS "portfolio_sectioncommon" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "section_type_id" integer NULL REFERENCES "portfolio_sectiontype" ("id") DEFERRABLE INITIALLY DEFERRED, "friendly_name" varchar(64) NOT NULL, "page_id" integer NULL REFERENCES "portfolio_pagecommon" ("id") DEFERRABLE INITIALLY DEFERRED, "position" integer NULL);
CREATE INDEX "portfolio_sectioncommon_section_type_id_acb95866" ON "portfolio_sectioncommon" ("section_type_id");
CREATE INDEX "portfolio_sectioncommon_page_id_b1950430" ON "portfolio_sectioncommon" ("page_id");
CREATE UNIQUE INDEX "portfolio_sectioncommon_page_id_position_4af46c91_uniq" ON "portfolio_sectioncommon" ("page_id", "position");
CREATE TABLE IF NOT EXISTS "portfolio_footerlink" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(12) NOT NULL, "url" varchar(256) NOT NULL, "position" varchar(8) NULL UNIQUE, "icon_id" integer NULL REFERENCES "portfolio_icon" ("id") DEFERRABLE INITIALLY DEFERRED, "link_edit_id" integer NULL REFERENCES "portfolio_linkedit" ("id") DEFERRABLE INITIALLY DEFERRED, "external" varchar(200) NULL, "link_for" varchar(24) NULL, "page_id" integer NULL REFERENCES "portfolio_pagecommon" ("id") DEFERRABLE INITIALLY DEFERRED, "section_id" integer NULL REFERENCES "portfolio_section" ("id") DEFERRABLE INITIALLY DEFERRED, "view" varchar(64) NOT NULL);
CREATE INDEX "portfolio_footerlink_icon_id_2fb3f441" ON "portfolio_footerlink" ("icon_id");
CREATE INDEX "portfolio_footerlink_link_edit_id_37887883" ON "portfolio_footerlink" ("link_edit_id");
CREATE INDEX "portfolio_footerlink_page_id_ca27af0c" ON "portfolio_footerlink" ("page_id");
CREATE INDEX "portfolio_footerlink_section_id_7e2a084a" ON "portfolio_footerlink" ("section_id");
CREATE TABLE IF NOT EXISTS "portfolio_navlink" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(12) NOT NULL, "url" varchar(256) NOT NULL, "position" varchar(8) NULL UNIQUE, "link_edit_id" integer NULL REFERENCES "portfolio_linkedit" ("id") DEFERRABLE INITIALLY DEFERRED, "external" varchar(200) NULL, "link_for" varchar(24) NULL, "page_id" integer NULL REFERENCES "portfolio_pagecommon" ("id") DEFERRABLE INITIALLY DEFERRED, "section_id" integer NULL REFERENCES "portfolio_section" ("id") DEFERRABLE INITIALLY DEFERRED, "view" varchar(64) NOT NULL);
CREATE INDEX "portfolio_navlink_link_edit_id_33e5d8e9" ON "portfolio_navlink" ("link_edit_id");
CREATE INDEX "portfolio_navlink_page_id_f824f393" ON "portfolio_navlink" ("page_id");
CREATE INDEX "portfolio_navlink_section_id_ccb52452" ON "portfolio_navlink" ("section_id");
CREATE TABLE IF NOT EXISTS "portfolio_collectionitemcommon" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "image" varchar(100) NOT NULL, "created" datetime NOT NULL, "spotlight" bool NOT NULL, "detail_view" varchar(64) NOT NULL, "friendly_name" varchar(64) NOT NULL, "parent_section_id" integer NULL REFERENCES "portfolio_sectioncommon" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "portfolio_collectionitemcommon_parent_section_id_fa0b1eb9" ON "portfolio_collectionitemcommon" ("parent_section_id");
CREATE TABLE IF NOT EXISTS "portfolio_section" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(64) NOT NULL, "slug" varchar(50) NOT NULL, "description" text NULL, "lang" varchar(5) NOT NULL, "common_id" integer NULL REFERENCES "portfolio_sectioncommon" ("id") DEFERRABLE INITIALLY DEFERRED, "detail_slug" varchar(50) NULL);
CREATE INDEX "portfolio_section_slug_12bcc770" ON "portfolio_section" ("slug");
CREATE INDEX "portfolio_section_common_id_4d1335ad" ON "portfolio_section" ("common_id");
CREATE INDEX "portfolio_section_detail_slug_b38505bf" ON "portfolio_section" ("detail_slug");
CREATE TABLE IF NOT EXISTS "portfolio_pagecommon" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "template_name" varchar(64) NOT NULL, "page_type_id" integer NULL REFERENCES "portfolio_pagetype" ("id") DEFERRABLE INITIALLY DEFERRED, "friendly_name" varchar(64) NOT NULL, "footer_link" bool NOT NULL, "footer_position" integer NULL UNIQUE);
CREATE INDEX "portfolio_pagecommon_page_type_id_e5d2c72b" ON "portfolio_pagecommon" ("page_type_id");
CREATE TABLE IF NOT EXISTS "portfolio_contactresponse" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "lang" varchar(5) NOT NULL, "name" varchar(32) NOT NULL, "slug" varchar(50) NULL, "message" text NOT NULL, "common_id" integer NULL REFERENCES "portfolio_contactresponsecommon" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "portfolio_contactresponse_lang_slug_447cdff7_uniq" ON "portfolio_contactresponse" ("lang", "slug");
CREATE INDEX "portfolio_contactresponse_slug_08c7ab06" ON "portfolio_contactresponse" ("slug");
CREATE INDEX "portfolio_contactresponse_common_id_aba39fc3" ON "portfolio_contactresponse" ("common_id");
CREATE TABLE IF NOT EXISTS "portfolio_message" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "subject" varchar(100) NOT NULL, "content" text NOT NULL, "contact_id" char(32) NOT NULL REFERENCES "portfolio_contact" ("id") DEFERRABLE INITIALLY DEFERRED, "sent" bool NOT NULL, "date_created" datetime NOT NULL, "date_sent" datetime NULL);
CREATE INDEX "portfolio_message_contact_id_5e9558e7" ON "portfolio_message" ("contact_id");
CREATE TABLE IF NOT EXISTS "portfolio_contactresponsecommon" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "friendly_name" varchar(32) NOT NULL, "action_id" integer NULL REFERENCES "portfolio_contactresponseaction" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "portfolio_contactresponsecommon_action_id_39ffcbd2" ON "portfolio_contactresponsecommon" ("action_id");
CREATE TABLE IF NOT EXISTS "portfolio_contactresponseaction" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(24) NOT NULL, "method" varchar(7) NOT NULL, "argument" varchar(32) NULL, "page_id" integer NULL REFERENCES "portfolio_pagecommon" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "portfolio_contactresponseaction_page_id_64c12405" ON "portfolio_contactresponseaction" ("page_id");
CREATE TABLE IF NOT EXISTS "portfolio_sociallink" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(12) NOT NULL, "url" varchar(256) NOT NULL, "view" varchar(64) NOT NULL, "link_for" varchar(24) NULL, "external" varchar(200) NULL, "icon_id" integer NULL REFERENCES "portfolio_icon" ("id") DEFERRABLE INITIALLY DEFERRED, "link_edit_id" integer NULL REFERENCES "portfolio_linkedit" ("id") DEFERRABLE INITIALLY DEFERRED, "page_id" integer NULL REFERENCES "portfolio_pagecommon" ("id") DEFERRABLE INITIALLY DEFERRED, "section_id" integer NULL REFERENCES "portfolio_section" ("id") DEFERRABLE INITIALLY DEFERRED, "position" varchar(6) NULL UNIQUE);
CREATE INDEX "portfolio_sociallink_icon_id_c2b78336" ON "portfolio_sociallink" ("icon_id");
CREATE INDEX "portfolio_sociallink_link_edit_id_9ac4ac06" ON "portfolio_sociallink" ("link_edit_id");
CREATE INDEX "portfolio_sociallink_page_id_2380cde5" ON "portfolio_sociallink" ("page_id");
CREATE INDEX "portfolio_sociallink_section_id_9aa8e02f" ON "portfolio_sociallink" ("section_id");
CREATE TABLE IF NOT EXISTS "portfolio_icon" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(64) NOT NULL, "icon_class" varchar(64) NOT NULL, "colour" varchar(7) NULL, "colour_value" varchar(7) NULL, "slug" varchar(50) NULL);
CREATE INDEX "portfolio_icon_slug_3abb480c" ON "portfolio_icon" ("slug");
